# Generated by Django 2.2.7 on 2019-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hotel', models.CharField(blank=True, max_length=50)),
                ('checkin', models.DateField(auto_now=True)),
                ('checkout', models.DateField()),
                ('amount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=40)),
                ('hotel_name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True, default=5000)),
                ('pic1', models.ImageField(blank=True, upload_to='')),
                ('pic2', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('pic3', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('pic4', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('pic5', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('pic6', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='KjHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.BigIntegerField(blank=True)),
                ('profile', models.FileField(default='media/default.jpg', upload_to='media/')),
            ],
        ),
    ]
